"""
DexMind — Telegram AI Agent (Vercel Lightweight Edition)
=========================================================
No heavy frameworks — pure requests + Telegram Bot API directly.
Vercel serverless compatible.

Image Fix:
- Webhook returns 200 instantly (avoids Vercel timeout)
- Image is fetched and sent in a background thread
- Image bytes sent via multipart/form-data (most reliable method)
"""

import os
import re
import json
import logging
import threading
import urllib.parse
from datetime import datetime
from io import BytesIO
from zoneinfo import ZoneInfo
from http.server import BaseHTTPRequestHandler

import requests

# ─────────────────────────── CONFIG ───────────────────────────────────────────

TELEGRAM_TOKEN     = os.getenv("TELEGRAM_TOKEN", "")
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY", "")
MODEL              = os.getenv("MODEL", "mistralai/mistral-7b-instruct:free")
WEBHOOK_SECRET     = os.getenv("WEBHOOK_SECRET", "dexmind_secret")

BOT_NAME     = "DexMind"
BOT_VERSION  = "3.23.26"
DEVELOPER    = "PraX"
DEV_TELEGRAM = "https://t.me/Dex_Error_404"
TIMEZONE     = ZoneInfo("Asia/Kolkata")

SYSTEM_PROMPT = (
    f"You are {BOT_NAME}, a helpful and friendly AI assistant inside a Telegram chat. "
    "Keep answers clear and concise. "
    "If weather data is provided, summarise it naturally. "
    "If date/time is provided, use it naturally."
)

MAX_HISTORY = 10

# ─────────────────────────── LOGGING ──────────────────────────────────────────

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

user_histories: dict = {}

# ─────────────────────────── TELEGRAM HELPERS ─────────────────────────────────

def tg_send(chat_id: int, text: str, parse_mode: str = "Markdown") -> None:
    try:
        requests.post(
            f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage",
            json={"chat_id": chat_id, "text": text, "parse_mode": parse_mode},
            timeout=10,
        )
    except Exception as e:
        logger.error("tg_send error: %s", e)


def tg_action(chat_id: int, action: str = "typing") -> None:
    try:
        requests.post(
            f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendChatAction",
            json={"chat_id": chat_id, "action": action},
            timeout=5,
        )
    except Exception:
        pass


def tg_send_photo_bytes(chat_id: int, img_bytes: bytes, caption: str = "") -> bool:
    """Send photo as raw bytes via multipart — most reliable method."""
    try:
        r = requests.post(
            f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendPhoto",
            data={"chat_id": chat_id, "caption": caption, "parse_mode": "Markdown"},
            files={"photo": ("image.jpg", BytesIO(img_bytes), "image/jpeg")},
            timeout=30,
        )
        result = r.json()
        if not result.get("ok"):
            logger.error("sendPhoto failed: %s", result)
            return False
        return True
    except Exception as e:
        logger.error("tg_send_photo_bytes error: %s", e)
        return False

# ─────────────────────────── IMAGE GENERATION ─────────────────────────────────

def _image_worker(prompt: str, chat_id: int) -> None:
    """
    Runs in background thread:
    1. Fetch image bytes from Pollinations.ai
    2. Send to Telegram as multipart upload
    """
    tg_action(chat_id, "upload_photo")

    encoded   = urllib.parse.quote(prompt.strip())
    image_url = (
        f"https://image.pollinations.ai/prompt/{encoded}"
        f"?width=1024&height=1024&nologo=true&enhance=true"
    )

    try:
        # Download image (can take 20-50s — OK in background thread)
        r = requests.get(image_url, timeout=55)
        r.raise_for_status()

        content_type = r.headers.get("content-type", "")
        if "image" not in content_type:
            raise ValueError(f"Unexpected content-type: {content_type}")

        success = tg_send_photo_bytes(
            chat_id,
            r.content,
            caption=f"🖼 *{prompt}*\n_Generated by DexMind × Pollinations.ai_ ✨"
        )

        if not success:
            tg_send(chat_id, "⚠️ Image ready but upload failed. Please try again!")

    except requests.Timeout:
        tg_send(chat_id, "⏱ Image generation took too long. Try a simpler prompt!")
    except Exception as e:
        logger.error("Image worker error: %s", e)
        tg_send(chat_id, "⚠️ Image generation failed. Please try again!")


def generate_image(prompt: str, chat_id: int) -> None:
    """
    Instantly send 'generating' message and start background thread.
    Vercel webhook handler gets 200 response immediately — no timeout.
    """
    if not prompt.strip():
        tg_send(chat_id,
            "⚠️ Please provide a prompt!\n\n"
            "*Example:*\n`/image a cute dog playing in park`"
        )
        return

    tg_send(chat_id, f"🎨 Generating: *{prompt}*\nThis may take 20-40 seconds...")
    tg_action(chat_id, "upload_photo")

    # Fire and forget — runs after Vercel returns 200
    t = threading.Thread(target=_image_worker, args=(prompt, chat_id), daemon=True)
    t.start()

# ─────────────────────────── WEATHER HELPER ───────────────────────────────────

_WEATHER_RE  = re.compile(
    r"\b(weather|temperature|forecast|rain|sunny|cloudy|hot|cold|humid)\b",
    re.IGNORECASE,
)
_LOCATION_RE = re.compile(r"\bin\s+([A-Za-z\s]+?)(?:[?!.,]|$)", re.IGNORECASE)


def get_weather(text: str) -> str:
    if not _WEATHER_RE.search(text):
        return ""
    m = _LOCATION_RE.search(text)
    loc = m.group(1).strip() if m else ""
    try:
        r = requests.get(f"https://wttr.in/{urllib.parse.quote(loc)}?format=3", timeout=6)
        r.raise_for_status()
        return f"[Live weather: {r.text.strip()}]"
    except Exception:
        return ""

# ─────────────────────────── DATETIME HELPER ──────────────────────────────────

_DATETIME_RE = re.compile(
    r"\b(time|date|day|today|now|current time|current date|kal|aaj|kitne baje)\b",
    re.IGNORECASE,
)


def get_datetime() -> str:
    now = datetime.now(TIMEZONE)
    return (
        f"[Current date & time (IST): "
        f"{now.strftime('%A, %d %B %Y')} | {now.strftime('%I:%M %p')}]"
    )

# ─────────────────────────── AI CALL ──────────────────────────────────────────

def ai_reply(user_id: int, user_text: str) -> str:
    history = user_histories.setdefault(user_id, [])

    parts = []
    w = get_weather(user_text)
    if w:
        parts.append(w)
    if _DATETIME_RE.search(user_text):
        parts.append(get_datetime())
    parts.append(user_text)

    content = "\n".join(parts).strip()
    history.append({"role": "user", "content": content})

    if len(history) > MAX_HISTORY:
        history[:] = history[-MAX_HISTORY:]

    messages = [{"role": "system", "content": SYSTEM_PROMPT}] + history

    try:
        r = requests.post(
            "https://openrouter.ai/api/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {OPENROUTER_API_KEY}",
                "Content-Type": "application/json",
            },
            json={
                "model": MODEL,
                "messages": messages,
                "max_tokens": 512,
                "temperature": 0.7,
            },
            timeout=25,
        )
        r.raise_for_status()
        reply = r.json()["choices"][0]["message"]["content"].strip()
        history.append({"role": "assistant", "content": reply})
        return reply or "⚠️ Empty response. Try again."

    except Exception as e:
        logger.error("OpenRouter error: %s", e)
        history.pop()
        return "⚠️ Couldn't reach AI right now. Please try again."

# ─────────────────────────── COMMAND HANDLERS ─────────────────────────────────

def handle_start(chat_id: int, first_name: str) -> None:
    now = datetime.now(TIMEZONE).strftime("%I:%M %p, %d %B %Y")
    tg_send(chat_id,
        f"👋 Hey {first_name}! I'm *{BOT_NAME}* — your personal AI assistant.\n"
        f"🕐 Current time (IST): {now}\n\n"
        "Try asking:\n"
        "• What's the weather in Mumbai?\n"
        "• What time is it?\n"
        "• Tell me a fun fact\n"
        "• `/image a sunset over mountains` 🎨\n\n"
        "Commands: /help  /clear  /model  /datetime  /image  /developer"
    )


def handle_help(chat_id: int) -> None:
    tg_send(chat_id,
        f"🧠 *{BOT_NAME} — Commands*\n\n"
        "/start           – Welcome message\n"
        "/help            – Show this help\n"
        "/clear           – Clear your chat history\n"
        "/model           – Show current AI model\n"
        "/datetime        – Show current date & time\n"
        "/image <prompt>  – Generate AI image 🎨\n"
        "/developer       – About the developer\n\n"
        "Just type anything to chat with me!\n"
        "Include a city name for live weather. 🌦\n\n"
        "*Image examples:*\n"
        "`/image a cute dog playing in park`\n"
        "`/image futuristic city at night`\n"
        "`/image mountain landscape watercolor`"
    )


def handle_clear(chat_id: int, user_id: int) -> None:
    user_histories.pop(user_id, None)
    tg_send(chat_id, "🗑️ Your conversation history has been cleared!")


def handle_model(chat_id: int) -> None:
    tg_send(chat_id, f"🤖 *Current AI Model:*\n`{MODEL}`")


def handle_datetime(chat_id: int) -> None:
    now = datetime.now(TIMEZONE)
    tg_send(chat_id,
        f"🗓 *Date & Time (IST)*\n\n"
        f"📅 Date : {now.strftime('%A, %d %B %Y')}\n"
        f"🕐 Time : {now.strftime('%I:%M:%S %p')}"
    )


def handle_developer(chat_id: int) -> None:
    tg_send(chat_id,
        f"👨‍💻 *Developer Info*\n\n"
        f"🧑 Name       : {DEVELOPER}\n"
        f"📬 Telegram   : {DEV_TELEGRAM}\n"
        f"🤖 Bot        : {BOT_NAME} v`{BOT_VERSION}`"
    )

# ─────────────────────────── UPDATE PROCESSOR ─────────────────────────────────

def process_update(data: dict) -> None:
    msg = data.get("message") or data.get("edited_message")
    if not msg:
        return

    chat_id    = msg["chat"]["id"]
    user_id    = msg["from"]["id"]
    first_name = msg["from"].get("first_name", "there")
    text       = msg.get("text", "").strip()

    if not text:
        return

    if text.startswith("/start"):
        handle_start(chat_id, first_name)
    elif text.startswith("/help"):
        handle_help(chat_id)
    elif text.startswith("/clear"):
        handle_clear(chat_id, user_id)
    elif text.startswith("/model"):
        handle_model(chat_id)
    elif text.startswith("/datetime"):
        handle_datetime(chat_id)
    elif text.startswith("/developer"):
        handle_developer(chat_id)
    elif text.startswith("/image"):
        prompt = text[6:].strip()
        generate_image(prompt, chat_id)
    else:
        tg_typing(chat_id)
        reply = ai_reply(user_id, text)
        tg_send(chat_id, reply)

# ─────────────────────────── VERCEL ENTRYPOINT ────────────────────────────────

class handler(BaseHTTPRequestHandler):

    def log_message(self, format, *args):
        pass

    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-Type", "text/plain")
        self.end_headers()
        self.wfile.write(f"{BOT_NAME} v{BOT_VERSION} is alive! 🧠".encode())

    def do_POST(self):
        content_length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(content_length)

        secret = self.headers.get("X-Telegram-Bot-Api-Secret-Token", "")
        if WEBHOOK_SECRET and secret != WEBHOOK_SECRET:
            self.send_response(403)
            self.end_headers()
            self.wfile.write(b"Forbidden")
            return

        try:
            data = json.loads(body)
            process_update(data)
        except Exception as e:
            logger.error("Webhook error: %s", e)
        finally:
            # Always return 200 immediately — background thread handles image
            self.send_response(200)
            self.end_headers()
            self.wfile.write(b"OK")
